# Generated by Django 4.1.4 on 2022-12-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=50, verbose_name='Enter State name ')),
                ('District', models.CharField(max_length=50, verbose_name='Enter District name')),
                ('center', models.CharField(max_length=50, verbose_name='Enter Center name')),
            ],
            options={
                'db_table': 'centers',
            },
        ),
    ]
